# Generated by Django 4.1.3 on 2022-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
